<?xml version="1.0"?>
<xsl:stylesheet xmlns:erp="http://www.wyona.org/erp/1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:param name="source">/tmp/invoice.xml</xsl:param>
    <xsl:param name="update">false</xsl:param>
    <xsl:template match="/">
        <open>
            <source:write xmlns:source="http://apache.org/cocoon/source/1.0">
                <source:source>
                    <xsl:value-of select="$source"/>
                </source:source>
                <xsl:if test="$update = 'true'">
                    <!--source:path>/erp:invoice/erp:content</source:path-->
                    <source:path>/invoice/content</source:path>
                </xsl:if>
                <source:fragment>
                    <xsl:choose>
                        <xsl:when test="$update = 'true'">
                            <xsl:copy-of select="/instanceData/invoice/*"/>
                        </xsl:when>
                        <xsl:otherwise>
                            <invoice xmlns="http://www.wyona.org/erp/1.0"
                                xmlns:erp="http://www.wyona.org/erp/1.0"
                                dt:dt-id="person"
                                dt:dt-namespace="http://www.wyona.org/erp/1.1"
                                dt:dt-version="1.1" xmlns:dt="http://www.wyona.org/dt/1.0">
                                <customer id="hugo"/>
                                <!-- NOTE: "niy" means "not invoiced yet" -->
                                <status>niy</status>
                                <description> Hugo</description>
                                <pdf href="160502.pdf"/>
                                <odt href="160502.odt"/>
                                <tasks>
                                    <task id="hugo-1"/>
                                    <task id="hugo-2"/>
                                    <task id="hugo-3"/>
                                </tasks>
                                <!-- Generated by invoice controller -->
                                <total-amount>...</total-amount>
                                <content>
                                    <xsl:attribute name="id"><xsl:value-of select="/instanceData/invoice/@id"/></xsl:attribute>
                                    <xsl:copy-of select="/instanceData/invoice/*"/>
                                </content>
                            </invoice>
                        </xsl:otherwise>
                    </xsl:choose>
                </source:fragment>
            </source:write>
        </open>
    </xsl:template>
</xsl:stylesheet>
